 spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: root
      url: jdbc:mysql://localhost:3306/comm1
      username: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      format-sql: true
